name: Extract zip
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          ZIPFILE=$(ls *.zip | head -n 1)
          echo "Found: $ZIPFILE"
          unzip -o "$ZIPFILE" -d .
          rm -f "$ZIPFILE"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Extract app files"
